In [1]:
import sys
from sklearn.metrics import roc_auc_score, log_loss
from sklearn.model_selection import train_test_split
import pandas as pd
import xgboost as xgb

sys.path.append("C:\\Users\\brady\\Documents\\FootballBetting\\FootballBetting\\processing")

from get_season_stats import GetTeamStats, get_multi_seasons

season_dir='C:\\Users\\brady\\Documents\\FootballBetting\\FootballBetting\\data\\results'
eos_stats_path='C:\\Users\\brady\\Documents\\FootballBetting\\FootballBetting\\data\\eos_stats\\SeasonSummaries.csv'

In [2]:
E1_1718 = GetTeamStats('E1', '1718', season_dir, eos_stats_path, include_odds=True)

In [3]:
test = []
for i in range(3):
    test.append(GetTeamStats('E{}'.format(i), '1718', season_dir, eos_stats_path, include_odds=True).getFixAndStats())

In [4]:
test[0].head()

,Date,HomeTeam,AwayTeam,B365H,B365D,B365A,BWH,BWD,BWA,IWH,...,At_Conceded_A,At_Shots_For_A,At_Shots_Ag_A,At_Shots_Tg_For_A,At_Shots_Tg_Ag_A,At_Fouls_For_A,At_Fouls_Ag_A,At_Bk_Pts_A,At_Promoted,At_Relegated
0,11/08/17,Arsenal,Leicester,1.53,4.50,6.50,1.50,4.60,6.75,1.47,...,38.0,192.0,297.0,62.0,100.0,250.0,164.0,435.0,0,0
1,31/03/18,Brighton,Leicester,2.70,3.20,2.62,2.70,3.10,2.80,2.75,...,38.0,192.0,297.0,62.0,100.0,250.0,164.0,435.0,0,0
2,13/01/18,Chelsea,Leicester,1.30,5.75,12.00,1.26,5.75,11.50,1.33,...,38.0,192.0,297.0,62.0,100.0,250.0,164.0,435.0,0,0
3,28/04/18,Crystal Palace,Leicester,2.04,3.60,3.79,2.05,3.30,3.80,2.00,...,38.0,192.0,297.0,62.0,100.0,250.0,164.0,435.0,0,0
4,31/01/18,Everton,Leicester,3.00,3.20,2.62,2.95,3.10,2.55,2.70,...,38.0,192.0,297.0,62.0,100.0,250.0,164.0,435.0,0,0

# Basic Benchmarking 
- Bet on home
- Measure by accuracy
- Single year test

In [5]:
import pandas as pd

for i in range(3):
    acc = abs(test[i][["HomeWin", "AwayWin", "Draw"]].values 
        - pd.DataFrame([[1] * len(test[i]), [0] * len(test[i]), [0] * len(test[i])]).T.values).mean()
    
    print("league {}: {}".format(i, acc))

league 0: 0.3631578947368421
league 1: 0.37922705314009664
league 2: 0.39473684210526316

## Findings
- Better than average
- Seems to matter in lower leagues
    - Possibly a feature

# Model V1
- Initial GBM model
- Use previous season stats to inform prediction

## Prep

In [7]:
from importlib import reload
from get_season_stats import get_multi_seasons

for i in range(3)
df_E0 = get_multi_seasons(1617, 5, season_dir, eos_stats_path, league='E0')

In [8]:
df_E0.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1140 entries, 0 to 379
Data columns (total 62 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               1140 non-null   datetime64[ns]
 1   HomeTeam           1140 non-null   object
 2   AwayTeam           1140 non-null   object
 3   HomeWin            1140 non-null   int64
 4   AwayWin            1140 non-null   int64
 5   Draw               1140 non-null   int64
 6   Ht_Position        1140 non-null   int64
 7   Ht_Points          1140 non-null   float64
 8   Ht_Win             1140 non-null   float64
 9   Ht_Draw            1140 non-null   float64
 10  Ht_Loss            1140 non-null   float64
 11  Ht_Scored          1140 non-null   float64
 12  Ht_Conceded        1140 non-null   float64
 13  Ht_Shots_For       1140 non-null   float64
 14  Ht_Shots_Ag        1140 non-null   float64
 15  Ht_Shots_Tg_For    1140 non-null   float64
 16  Ht_Shots_Tg_Ag     1140 non-null   float64
 17  Ht_Fouls_For       1140 non-null   float64
 18  Ht_Fouls_Ag        1140 non-null   float64
 19  Ht_Bk_Pts          1140 non-null   float64
 20  Ht_Win_H           1140 non-null   float64
 21  Ht_Draw_H          1140 non-null   float64
 22  Ht_Loss_H          1140 non-null   float64
 23  Ht_Scored_H        1140 non-null   float64
 24  Ht_Conceded_H      1140 non-null   float64
 25  Ht_Shots_For_H     1140 non-null   float64
 26  Ht_Shots_Ag_H      1140 non-null   float64
 27  Ht_Shots_Tg_For_H  1140 non-null   float64
 28  Ht_Shots_Tg_Ag_H   1140 non-null   float64
 29  Ht_Fouls_For_H     1140 non-null   float64
 30  Ht_Fouls_Ag_H      1140 non-null   float64
 31  Ht_Bk_Pts_H        1140 non-null   float64
 32  Ht_Promoted        1140 non-null   int64
 33  Ht_Relegated       1140 non-null   int64
 34  At_Position        1140 non-null   int64
 35  At_Points          1140 non-null   float64
 36  At_Win             1140 non-null   float64
 37  At_Draw            1140 non-null   float64
 38  At_Loss            1140 non-null   float64
 39  At_Scored          1140 non-null   float64
 40  At_Conceded        1140 non-null   float64
 41  At_Shots_For       1140 non-null   float64
 42  At_Shots_Ag        1140 non-null   float64
 43  At_Shots_Tg_For    1140 non-null   float64
 44  At_Shots_Tg_Ag     1140 non-null   float64
 45  At_Fouls_For       1140 non-null   float64
 46  At_Fouls_Ag        1140 non-null   float64
 47  At_Bk_Pts          1140 non-null   float64
 48  At_Win_A           1140 non-null   float64
 49  At_Draw_A          1140 non-null   float64
 50  At_Loss_A          1140 non-null   float64
 51  At_Scored_A        1140 non-null   float64
 52  At_Conceded_A      1140 non-null   float64
 53  At_Shots_For_A     1140 non-null   float64
 54  At_Shots_Ag_A      1140 non-null   float64
 55  At_Shots_Tg_For_A  1140 non-null   float64
 56  At_Shots_Tg_Ag_A   1140 non-null   float64
 57  At_Fouls_For_A     1140 non-null   float64
 58  At_Fouls_Ag_A      1140 non-null   float64
 59  At_Bk_Pts_A        1140 non-null   float64
 60  At_Promoted        1140 non-null   int64
 61  At_Relegated       1140 non-null   int64
dtypes: datetime64[ns](1), float64(50), int64(9), object(2)
memory usage: 561.1+ KB